version: '3.8'
services:
  web:
    build: .
    image: pratikbhongale/static_site:latest
    ports:
     - "9090:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
